-- Create the new 'styles' table
CREATE TABLE styles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level VARCHAR(50) NOT NULL,
    reference_id VARCHAR(255) NOT NULL,
    css_content TEXT,
    CONSTRAINT uk_styles_level_refid UNIQUE (level, reference_id)
);

-- Drop the old 'race_styles' table (it's unused/replaced)
DROP TABLE IF EXISTS race_styles;

-- Add a default global style
INSERT INTO styles (level, reference_id, css_content)
VALUES ('DEFAULT', 'GLOBAL_DEFAULT', ':root { --default-bg: #f5f5f5; }');

